version: '3'
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.4
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j-store:/data
      - ./import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      

  python:
    container_name: python
    build: ./python_dict
    ports:
      - 7878:7878
    volumes: 
      - ./python_dict:/dic
    extra_hosts:                  # 追加
            - localhost:172.18.0.1
    environment:
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true

# volumes:
#   neo4j-store:
#     driver: local